# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
     - main
     - feature/*
  paths:
    include:
     - AZTerraform/*
     - azure-pipelines.yml

stages:
- stage: validate
  jobs:
  - job: tf_validate
    pool:
      name: "AWS VM"
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.7.5'
    
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\AZTerraform\dev'
        backendAzureRmUseEntraIdForAuthentication: false
        backendServiceArm: 'Kr-Test-Sub(7653a001-c28d-4ce2-9ec3-c6cdd6a7f98f)'
        backendAzureRmResourceGroupName: 'terraform-state-rg'
        backendAzureRmStorageAccountName: 'tfdevbackend2026kr'
        backendAzureRmContainerName: 'tfstatekr'
        backendAzureRmKey: 'dev.terraform.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/AZTerraform/dev'

- stage: dev_deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: terraform_apply_dev
    pool:
      name: "AWS VM"
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.7.5'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/AZTerraform/dev'
        backendAzureRmUseEntraIdForAuthentication: false
        backendServiceArm: 'Kr-Test-Sub(7653a001-c28d-4ce2-9ec3-c6cdd6a7f98f)'
        backendAzureRmResourceGroupName: 'terraform-state-rg'
        backendAzureRmStorageAccountName: 'tfdevbackend2026kr'
        backendAzureRmContainerName: 'tfstatekr'
        backendAzureRmKey: 'dev.terraform.tfstate'  
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/AZTerraform/dev'
        commandOptions: '--auto-approve'
        environmentServiceNameAzureRM: 'Kr-Test-Sub(7653a001-c28d-4ce2-9ec3-c6cdd6a7f98f)'

- stage: stage_deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: terraform_apply_stage
    pool:
      name: "AWS VM"
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.7.5'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/AZTerraform/staging'
        backendAzureRmUseEntraIdForAuthentication: false
        backendServiceArm: 'Kr-Test-Sub(7653a001-c28d-4ce2-9ec3-c6cdd6a7f98f)'
        backendAzureRmResourceGroupName: 'terraform-state-rg'
        backendAzureRmStorageAccountName: 'tfstagebackend2026kr'
        backendAzureRmContainerName: 'tfstatekr'
        backendAzureRmKey: 'stage.terraform.tfstate'  
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/AZTerraform/staging'
        commandOptions: '--auto-approve'
        environmentServiceNameAzureRM: 'Kr-Test-Sub(7653a001-c28d-4ce2-9ec3-c6cdd6a7f98f)'
    
    
